/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AppState } from "./global/store";
export { AppState } from "./global/store";
export namespace Components {
    interface AppContent {
    }
    interface AppFooter {
    }
    interface AppHeader {
        "headerTitle": string;
    }
    interface AppMenu {
    }
    interface AppPuzzlePiece {
        "label": string;
        "pieceId": keyof AppState;
    }
    interface AppRoot {
    }
    interface PageAboutUs {
    }
    interface PageHome {
    }
    interface PageIntro {
    }
    interface PagePuzzle {
    }
    interface PageQ1 {
    }
    interface PageQ3 {
    }
    interface PageTeil1 {
    }
    interface PageTeil2 {
    }
}
declare global {
    interface HTMLAppContentElement extends Components.AppContent, HTMLStencilElement {
    }
    var HTMLAppContentElement: {
        prototype: HTMLAppContentElement;
        new (): HTMLAppContentElement;
    };
    interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {
    }
    var HTMLAppFooterElement: {
        prototype: HTMLAppFooterElement;
        new (): HTMLAppFooterElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {
    }
    var HTMLAppMenuElement: {
        prototype: HTMLAppMenuElement;
        new (): HTMLAppMenuElement;
    };
    interface HTMLAppPuzzlePieceElement extends Components.AppPuzzlePiece, HTMLStencilElement {
    }
    var HTMLAppPuzzlePieceElement: {
        prototype: HTMLAppPuzzlePieceElement;
        new (): HTMLAppPuzzlePieceElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLPageAboutUsElement extends Components.PageAboutUs, HTMLStencilElement {
    }
    var HTMLPageAboutUsElement: {
        prototype: HTMLPageAboutUsElement;
        new (): HTMLPageAboutUsElement;
    };
    interface HTMLPageHomeElement extends Components.PageHome, HTMLStencilElement {
    }
    var HTMLPageHomeElement: {
        prototype: HTMLPageHomeElement;
        new (): HTMLPageHomeElement;
    };
    interface HTMLPageIntroElement extends Components.PageIntro, HTMLStencilElement {
    }
    var HTMLPageIntroElement: {
        prototype: HTMLPageIntroElement;
        new (): HTMLPageIntroElement;
    };
    interface HTMLPagePuzzleElement extends Components.PagePuzzle, HTMLStencilElement {
    }
    var HTMLPagePuzzleElement: {
        prototype: HTMLPagePuzzleElement;
        new (): HTMLPagePuzzleElement;
    };
    interface HTMLPageQ1Element extends Components.PageQ1, HTMLStencilElement {
    }
    var HTMLPageQ1Element: {
        prototype: HTMLPageQ1Element;
        new (): HTMLPageQ1Element;
    };
    interface HTMLPageQ3Element extends Components.PageQ3, HTMLStencilElement {
    }
    var HTMLPageQ3Element: {
        prototype: HTMLPageQ3Element;
        new (): HTMLPageQ3Element;
    };
    interface HTMLPageTeil1Element extends Components.PageTeil1, HTMLStencilElement {
    }
    var HTMLPageTeil1Element: {
        prototype: HTMLPageTeil1Element;
        new (): HTMLPageTeil1Element;
    };
    interface HTMLPageTeil2Element extends Components.PageTeil2, HTMLStencilElement {
    }
    var HTMLPageTeil2Element: {
        prototype: HTMLPageTeil2Element;
        new (): HTMLPageTeil2Element;
    };
    interface HTMLElementTagNameMap {
        "app-content": HTMLAppContentElement;
        "app-footer": HTMLAppFooterElement;
        "app-header": HTMLAppHeaderElement;
        "app-menu": HTMLAppMenuElement;
        "app-puzzle-piece": HTMLAppPuzzlePieceElement;
        "app-root": HTMLAppRootElement;
        "page-about-us": HTMLPageAboutUsElement;
        "page-home": HTMLPageHomeElement;
        "page-intro": HTMLPageIntroElement;
        "page-puzzle": HTMLPagePuzzleElement;
        "page-q1": HTMLPageQ1Element;
        "page-q3": HTMLPageQ3Element;
        "page-teil-1": HTMLPageTeil1Element;
        "page-teil-2": HTMLPageTeil2Element;
    }
}
declare namespace LocalJSX {
    interface AppContent {
    }
    interface AppFooter {
    }
    interface AppHeader {
        "headerTitle"?: string;
    }
    interface AppMenu {
    }
    interface AppPuzzlePiece {
        "label"?: string;
        "pieceId"?: keyof AppState;
    }
    interface AppRoot {
    }
    interface PageAboutUs {
    }
    interface PageHome {
    }
    interface PageIntro {
    }
    interface PagePuzzle {
    }
    interface PageQ1 {
    }
    interface PageQ3 {
    }
    interface PageTeil1 {
    }
    interface PageTeil2 {
    }
    interface IntrinsicElements {
        "app-content": AppContent;
        "app-footer": AppFooter;
        "app-header": AppHeader;
        "app-menu": AppMenu;
        "app-puzzle-piece": AppPuzzlePiece;
        "app-root": AppRoot;
        "page-about-us": PageAboutUs;
        "page-home": PageHome;
        "page-intro": PageIntro;
        "page-puzzle": PagePuzzle;
        "page-q1": PageQ1;
        "page-q3": PageQ3;
        "page-teil-1": PageTeil1;
        "page-teil-2": PageTeil2;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-content": LocalJSX.AppContent & JSXBase.HTMLAttributes<HTMLAppContentElement>;
            "app-footer": LocalJSX.AppFooter & JSXBase.HTMLAttributes<HTMLAppFooterElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-menu": LocalJSX.AppMenu & JSXBase.HTMLAttributes<HTMLAppMenuElement>;
            "app-puzzle-piece": LocalJSX.AppPuzzlePiece & JSXBase.HTMLAttributes<HTMLAppPuzzlePieceElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "page-about-us": LocalJSX.PageAboutUs & JSXBase.HTMLAttributes<HTMLPageAboutUsElement>;
            "page-home": LocalJSX.PageHome & JSXBase.HTMLAttributes<HTMLPageHomeElement>;
            "page-intro": LocalJSX.PageIntro & JSXBase.HTMLAttributes<HTMLPageIntroElement>;
            "page-puzzle": LocalJSX.PagePuzzle & JSXBase.HTMLAttributes<HTMLPagePuzzleElement>;
            "page-q1": LocalJSX.PageQ1 & JSXBase.HTMLAttributes<HTMLPageQ1Element>;
            "page-q3": LocalJSX.PageQ3 & JSXBase.HTMLAttributes<HTMLPageQ3Element>;
            "page-teil-1": LocalJSX.PageTeil1 & JSXBase.HTMLAttributes<HTMLPageTeil1Element>;
            "page-teil-2": LocalJSX.PageTeil2 & JSXBase.HTMLAttributes<HTMLPageTeil2Element>;
        }
    }
}
